version: "3.3"
services:
    redis:
      image: redis
      volumes:
        - ./redis_data:/data
      ports:
        - "6379:6379"
    stack-overflow-crawler:
      build:
        dockerfile: ./Dockerfile
        context: crawlers/stack-overflow/
      command: python ./main.py
    reddit-crawler:
      build:
        dockerfile: ./Dockerfile
        context: crawlers/reddit/
      command: python ./main.py