version: "3.3"
services:
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - "127.0.0.1:5672:5672"
        - "127.0.0.1:15672:15672"
    redis:
      image: redis
      volumes:
        - ./redis_data:/data
      ports:
        - "6379:6379"
    stack-overflow-crawler:
      build:
        dockerfile: ./Dockerfile
        context: crawlers/stack-overflow/
      command: python ./main.py
    telegram:
      build:
        dockerfile: ./Dockerfile
        context: crawlers/telegram/
      command: python ./main.py
